[package]
name = "dioxus-showcase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.0", features = ["web"] }
dioxus-markdown = { path = "../../", features = ["maths"] }
